// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type HistoricSearch struct {
	HistoricSearchID int32          `json:"historic_search_id"`
	Username         sql.NullString `json:"username"`
	SearchString     string         `json:"search_string"`
}

type Preference struct {
	Preference string `json:"preference"`
}

type User struct {
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	Middlename sql.NullString `json:"middlename"`
	Surname    string         `json:"surname"`
	Password   string         `json:"password"`
}

type UserPreference struct {
	Username   string `json:"username"`
	Preference string `json:"preference"`
}
