// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Document struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	FirstArea   string         `json:"first_area"`
	SecondArea  sql.NullString `json:"second_area"`
	Link        sql.NullString `json:"link"`
	Description sql.NullString `json:"description"`
	BasedOn     sql.NullString `json:"based_on"`
	Grantor     sql.NullString `json:"grantor"`
	Deadline    string         `json:"deadline"`
}

type HistoricSearch struct {
	HistoricSearchID int32     `json:"historic_search_id"`
	UserID           int32     `json:"user_id"`
	SearchString     string    `json:"search_string"`
	SearchDatetime   time.Time `json:"search_datetime"`
}

type User struct {
	UserID    int32          `json:"user_id"`
	Name      string         `json:"name"`
	Surname   string         `json:"surname"`
	AuthID    string         `json:"auth_id"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

type UserPreference struct {
	UserID     int32  `json:"user_id"`
	Preference string `json:"preference"`
}
