// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addDocument = `-- name: AddDocument :one
INSERT INTO documents(name, type, first_area, second_area, link, description, based_on, grantor, currency, amount, deadline, user_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, user_id, name, type, first_area, second_area, link, description, based_on, grantor, currency, amount, deadline
`

type AddDocumentParams struct {
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	FirstArea   string         `json:"first_area"`
	SecondArea  sql.NullString `json:"second_area"`
	Link        sql.NullString `json:"link"`
	Description sql.NullString `json:"description"`
	BasedOn     sql.NullString `json:"based_on"`
	Grantor     sql.NullString `json:"grantor"`
	Currency    string         `json:"currency"`
	Amount      string         `json:"amount"`
	Deadline    string         `json:"deadline"`
	UserID      sql.NullInt32  `json:"user_id"`
}

func (q *Queries) AddDocument(ctx context.Context, arg AddDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, addDocument,
		arg.Name,
		arg.Type,
		arg.FirstArea,
		arg.SecondArea,
		arg.Link,
		arg.Description,
		arg.BasedOn,
		arg.Grantor,
		arg.Currency,
		arg.Amount,
		arg.Deadline,
		arg.UserID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.FirstArea,
		&i.SecondArea,
		&i.Link,
		&i.Description,
		&i.BasedOn,
		&i.Grantor,
		&i.Currency,
		&i.Amount,
		&i.Deadline,
	)
	return i, err
}

const addPreference = `-- name: AddPreference :one
INSERT INTO user_preferences(user_id,preference) VALUES ($1,$2) RETURNING user_id, preference
`

type AddPreferenceParams struct {
	UserID     int32  `json:"user_id"`
	Preference string `json:"preference"`
}

func (q *Queries) AddPreference(ctx context.Context, arg AddPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, addPreference, arg.UserID, arg.Preference)
	var i UserPreference
	err := row.Scan(&i.UserID, &i.Preference)
	return i, err
}

const countAllDocuments = `-- name: CountAllDocuments :one
SELECT COUNT(*) FROM documents
`

func (q *Queries) CountAllDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHistoricSearch = `-- name: CreateHistoricSearch :one
INSERT INTO historic_searches(user_id,search_string) VALUES ($1,$2) RETURNING historic_search_id, user_id, search_string, search_datetime
`

type CreateHistoricSearchParams struct {
	UserID       int32  `json:"user_id"`
	SearchString string `json:"search_string"`
}

func (q *Queries) CreateHistoricSearch(ctx context.Context, arg CreateHistoricSearchParams) (HistoricSearch, error) {
	row := q.db.QueryRowContext(ctx, createHistoricSearch, arg.UserID, arg.SearchString)
	var i HistoricSearch
	err := row.Scan(
		&i.HistoricSearchID,
		&i.UserID,
		&i.SearchString,
		&i.SearchDatetime,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(name, surname, auth_id) VALUES ($1, $2, $3) RETURNING user_id, name, surname, auth_id, avatar_url
`

type CreateUserParams struct {
	Name    string `json:"name"`
	Surname string `json:"surname"`
	AuthID  string `json:"auth_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Surname, arg.AuthID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Surname,
		&i.AuthID,
		&i.AvatarUrl,
	)
	return i, err
}

const deleteAvatar = `-- name: DeleteAvatar :exec
UPDATE users SET avatar_url = NULL WHERE user_id = $1
`

func (q *Queries) DeleteAvatar(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteAvatar, userID)
	return err
}

const deleteHistoricSearch = `-- name: DeleteHistoricSearch :exec
DELETE FROM historic_searches WHERE historic_search_id = $1
`

func (q *Queries) DeleteHistoricSearch(ctx context.Context, historicSearchID int32) error {
	_, err := q.db.ExecContext(ctx, deleteHistoricSearch, historicSearchID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, user_id, name, type, first_area, second_area, link, description, based_on, grantor, currency, amount, deadline from documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id int32) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.FirstArea,
		&i.SecondArea,
		&i.Link,
		&i.Description,
		&i.BasedOn,
		&i.Grantor,
		&i.Currency,
		&i.Amount,
		&i.Deadline,
	)
	return i, err
}

const getTrendingSearches = `-- name: GetTrendingSearches :many
SELECT search_string, COUNT(*) AS count
FROM historic_searches
WHERE search_datetime >= date_trunc('day', NOW() AT TIME ZONE 'UTC')
    AND search_datetime <  date_trunc('day', NOW() AT TIME ZONE 'UTC') + INTERVAL '1 day'
GROUP BY search_string
ORDER BY count DESC
LIMIT $1
`

type GetTrendingSearchesRow struct {
	SearchString string `json:"search_string"`
	Count        int64  `json:"count"`
}

// Búquedas realizadas hoy según UTC.
func (q *Queries) GetTrendingSearches(ctx context.Context, limit int32) ([]GetTrendingSearchesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrendingSearches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrendingSearchesRow
	for rows.Next() {
		var i GetTrendingSearchesRow
		if err := rows.Scan(&i.SearchString, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAuthID = `-- name: GetUserByAuthID :one
SELECT user_id, name, surname, auth_id, avatar_url FROM users WHERE auth_id = $1
`

func (q *Queries) GetUserByAuthID(ctx context.Context, authID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAuthID, authID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Surname,
		&i.AuthID,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, name, surname, auth_id, avatar_url FROM users WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Surname,
		&i.AuthID,
		&i.AvatarUrl,
	)
	return i, err
}

const listAllDocuments = `-- name: ListAllDocuments :many
SELECT id, user_id, name, type, first_area, second_area, link, description, based_on, grantor, currency, amount, deadline FROM documents LIMIT $1 OFFSET $2
`

type ListAllDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllDocuments(ctx context.Context, arg ListAllDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listAllDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.FirstArea,
			&i.SecondArea,
			&i.Link,
			&i.Description,
			&i.BasedOn,
			&i.Grantor,
			&i.Currency,
			&i.Amount,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByUser = `-- name: ListDocumentsByUser :many
SELECT id, user_id, name, type, first_area, second_area, link, description, based_on, grantor, currency, amount, deadline FROM documents WHERE user_id = $1 LIMIT $2 OFFSET $3
`

type ListDocumentsByUserParams struct {
	UserID sql.NullInt32 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListDocumentsByUser(ctx context.Context, arg ListDocumentsByUserParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.FirstArea,
			&i.SecondArea,
			&i.Link,
			&i.Description,
			&i.BasedOn,
			&i.Grantor,
			&i.Currency,
			&i.Amount,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoricSearchesFromUser = `-- name: ListHistoricSearchesFromUser :many
SELECT search_string, search_datetime FROM historic_searches WHERE user_id = $1 ORDER BY search_datetime DESC
`

type ListHistoricSearchesFromUserRow struct {
	SearchString   string    `json:"search_string"`
	SearchDatetime time.Time `json:"search_datetime"`
}

func (q *Queries) ListHistoricSearchesFromUser(ctx context.Context, userID int32) ([]ListHistoricSearchesFromUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listHistoricSearchesFromUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHistoricSearchesFromUserRow
	for rows.Next() {
		var i ListHistoricSearchesFromUserRow
		if err := rows.Scan(&i.SearchString, &i.SearchDatetime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferencesFromUser = `-- name: ListPreferencesFromUser :many
SELECT preference FROM user_preferences WHERE user_id = $1
`

func (q *Queries) ListPreferencesFromUser(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPreferencesFromUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var preference string
		if err := rows.Scan(&preference); err != nil {
			return nil, err
		}
		items = append(items, preference)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, name, surname, auth_id, avatar_url FROM users ORDER BY user_id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Surname,
			&i.AuthID,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllPreferenceFromUser = `-- name: RemoveAllPreferenceFromUser :exec
DELETE FROM user_preferences WHERE user_id = $1
`

func (q *Queries) RemoveAllPreferenceFromUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllPreferenceFromUser, userID)
	return err
}

const removeDocument = `-- name: RemoveDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) RemoveDocument(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, removeDocument, id)
	return err
}

const removePreference = `-- name: RemovePreference :exec
DELETE FROM user_preferences WHERE user_id = $1 AND preference = $2
`

type RemovePreferenceParams struct {
	UserID     int32  `json:"user_id"`
	Preference string `json:"preference"`
}

func (q *Queries) RemovePreference(ctx context.Context, arg RemovePreferenceParams) error {
	_, err := q.db.ExecContext(ctx, removePreference, arg.UserID, arg.Preference)
	return err
}

const updateDocument = `-- name: UpdateDocument :exec
UPDATE documents SET name = $2, type = $3, first_area = $4, second_area = $5, link = $6, description = $7, based_on = $8, grantor = $9, currency = $10, amount = $11, deadline = $12, user_id = $13 WHERE id = $1
`

type UpdateDocumentParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	FirstArea   string         `json:"first_area"`
	SecondArea  sql.NullString `json:"second_area"`
	Link        sql.NullString `json:"link"`
	Description sql.NullString `json:"description"`
	BasedOn     sql.NullString `json:"based_on"`
	Grantor     sql.NullString `json:"grantor"`
	Currency    string         `json:"currency"`
	Amount      string         `json:"amount"`
	Deadline    string         `json:"deadline"`
	UserID      sql.NullInt32  `json:"user_id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, updateDocument,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.FirstArea,
		arg.SecondArea,
		arg.Link,
		arg.Description,
		arg.BasedOn,
		arg.Grantor,
		arg.Currency,
		arg.Amount,
		arg.Deadline,
		arg.UserID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET name = $2, surname = $3 WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID  int32  `json:"user_id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.UserID, arg.Name, arg.Surname)
	return err
}

const uploadAvatar = `-- name: UploadAvatar :exec
UPDATE users SET avatar_url = $2 WHERE user_id = $1
`

type UploadAvatarParams struct {
	UserID    int32          `json:"user_id"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) UploadAvatar(ctx context.Context, arg UploadAvatarParams) error {
	_, err := q.db.ExecContext(ctx, uploadAvatar, arg.UserID, arg.AvatarUrl)
	return err
}
