# Config file for Air
root = "."
tmp_dir = "tmp"

[build]
# Este comando se ejecuta ante cualquier cambio.
# Requsitos:
# chmod +x resources/scripts/recompile.sh
# chmod +x resources/scripts/sqlc/runSQLC.sh
# chmod +x resources/scripts/templ/runTEMPL.sh
cmd = "./resources/scripts/recompile.sh"

bin = "tmp/main"
include_ext = ["go", "templ", "temp", "html", "css", "png", "svg", "sql"]
include_dir = ["static", "database", "app"]

# Si no se excluye app/database, se entra en un ciclo infinito al ejecutar SQLC.
exclude_dir = ["assets", "tmp", "vendor", "resources", "app/database"]

include_file = []
exclude_file = []

# Se añade una regla para excluir TODOS los archivos .go dentro de app/views.
# Si no se coloca esto, se entra en un bucle infinito cuando se ejecuta 'templ generate'.
exclude_regex = ["_test.go", "app/views/.*\\.go$"]
exclude_unchanged = false
follow_symlink = false
log = "air.log"
poll = false
poll_interval = 500 # ms
stop_on_error = false
send_interrupt = false
kill_delay = 500 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no value is provided, use the default color.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

