services: # Development.
  app:
    build:
      target: dev
    volumes:
      - .:/app
    environment:
      GIN_MODE: debug

  db:
    volumes:
      # Database used by Atlas.
      - ./database/init:/docker-entrypoint-initdb.d
