services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:15
    container_name: scifi-search-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_LOGGING_COLLECTOR: "off"
      POSTGRES_LOG_MIN_MESSAGES: "WARNING"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - tpe-db-data:/var/lib/postgresql/data
      - ./logs/db:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -p ${DB_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Aplicación
  app:
    build:
      context: .
      target: production
    container_name: tpe-app-1
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_started
      nats:
        condition: service_started
      supertokens:
        condition: service_started
      minio:
        condition: service_started
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable"
      MEILI_URL: "${MEILI_URL}"
      MEILI_MASTER_KEY: "${MEILI_KEY}"
      SUPERTOKENS_URL: "${SUPERTOKENS_URL}"
      NATS_HOST: "nats"
      NATS_PORT: "4222"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      MINIO_HOST: "${MINIO_HOST}"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_BUCKET: "${MINIO_BUCKET}"
    env_file:
      - .env
    volumes:
      - ./logs/app:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  # Motor de búsqueda MeiliSearch
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "${MEILI_PORT}:${MEILI_PORT}"
    volumes:
      - ./meili_data:/meili_data
      - ./logs/meili:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      MEILI_MASTER_KEY: "${MEILI_KEY}"
    restart: always

  nats:
    image: nats:latest
    command:
      - "-DV=false"
    ports:
      - "4222:4222"
    volumes:
      - ./logs/nats:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  # Servicio de autenticación SuperTokens
  supertokens:
    image: supertokens/supertokens-core:dev-branch-11.0
    container_name: supertokens
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}"
      SUPERTOKENS_LOG_LEVEL: "warn"
    ports:
      - "${SUPERTOKENS_PORT}:${SUPERTOKENS_PORT}"
    volumes:
      - ./logs/supertokens:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  # Almacenamiento de objetos MinIO.
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # API S3-compatible
      - "9001:9001" # Panel web
    volumes:
      - ./minio_data:/data
      - ./logs/minio:/var/log
    restart: always

volumes:
  tpe-db-data:
