services: # Development.
  app:
    build:
      target: dev
    volumes:
      - .:/app
    environment:
      GIN_MODE: debug

  db:
    volumes: # Override.
      - postgres-data:/var/lib/postgresql/data
      - ./database/init/production:/docker-entrypoint-initdb.d/production:ro
      - ./database/init/development:/docker-entrypoint-initdb.d/development:ro
      # Schema not needed because Atlas will apply the migrations.
