services: # Desarrolo.
  app:
    build:
      target: dev
    volumes:
      - .:/app
      - /app/node_modules # (Volumen anónimo)
    environment:
      GIN_MODE: debug

  db:
    volumes:
      # Base de datos utilizada por atlas.
      - ./database/init:/docker-entrypoint-initdb.d
