services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:15
    container_name: scifi-search-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_LOGGING_COLLECTOR: "off"
      POSTGRES_LOG_MIN_MESSAGES: "WARNING"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - tpe-db-data:/var/lib/postgresql/data
      - ./logs/db:/var/log
      - ./database/init:/docker-entrypoint-initdb.d # Ejecuta cada archivo en la carpeta de acuerdo al orden alfabético.
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -p ${DB_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # =================================================================================================

  # Aplicación
  app:
    build:
      context: .
      target: production
    container_name: tpe-app-1
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_started
      supertokens:
        condition: service_started
      minio:
        condition: service_started
    environment:
      DATABASE_URL: "${DB_URL}"
      MEILI_URL: "${MEILI_URL}"
      MEILI_MASTER_KEY: "${MEILI_KEY}"
      SUPERTOKENS_URL: "${SUPERTOKENS_URL}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      MINIO_HOST: "${MINIO_HOST}"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_BUCKET: "${MINIO_BUCKET}"
    env_file:
      - .env
    volumes:
      - ./logs/app:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  # =================================================================================================

  # Motor de búsqueda MeiliSearch
  meilisearch:
    image: getmeili/meilisearch:v1.31.0 # "latest" si se desea utilizar la última versión.
    container_name: meilisearch
    ports:
      - "${MEILI_PORT}:${MEILI_PORT}"
    volumes:
      - ./meili_data:/meili_data
      - ./logs/meili:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      MEILI_MASTER_KEY: "${MEILI_KEY}"
    restart: always

  # =================================================================================================

  # Servicio de autenticación SuperTokens
  supertokens:
    image: supertokens/supertokens-core:dev-branch-11.0
    container_name: supertokens
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRESQL_CONNECTION_URI: "${DB_URL}"
      SUPERTOKENS_LOG_LEVEL: "warn"
    ports:
      - "${SUPERTOKENS_PORT}:${SUPERTOKENS_PORT}"
    volumes:
      - ./logs/supertokens:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  # =================================================================================================

  # Almacenamiento de objetos MinIO.
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # API S3-compatible.
      - "9001:9001" # Panel web.
    volumes:
      - ./minio_data:/data
      - ./logs/minio:/var/log
    restart: always

  # =================================================================================================

  # Simulación de emails.
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI.
    logging:
      driver: local
      options:
        max-size: "5m"
        max-file: "2"

# =================================================================================================

volumes:
  tpe-db-data:
# =================================================================================================
