services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:15
    container_name: scifi-search-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      # Únicamente se muestran warnings en la consola,
      # para reducir la verborragia.
      POSTGRES_LOGGING_COLLECTOR: "off"
      POSTGRES_LOG_MIN_MESSAGES: "WARNING"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      # - ./database/schema:/docker-entrypoint-initdb.d
      # Si la línea anteriro se descomenta, Postgres va a
      # cargar automáticamente el SQL cada vez que el contenedor
      # se inicialice. Si se utiliza Atlas, este realiza dicho
      # trabajo, por lo que la línea debe mantenerse comentada.
      - tpe-db-data:/var/lib/postgresql/data
      - ./logs/db:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Aplicación
  app:
    build:
      context: .
      target: dev # Cambiar a 'production' en producción
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_started
      nats:
        condition: service_started
      supertokens:
        condition: service_started
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable"
      MEILI_URL: "${MEILI_URL}"
      MEILI_MASTER_KEY: "${MEILI_KEY}"
      SUPERTOKENS_URL: "${SUPERTOKENS_URL}"
      NATS_HOST: "nats"
      NATS_PORT: "4222"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs/app:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  # Motor de búsqueda MeiliSearch
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    # Se reduce la verborragia
    # de la aplicación.
    command:
      #- "--no-analytics"
      #- "--env"
      #- "production"
      #- "--log-level"
      #- "error"
    ports:
      - "${MEILI_PORT}:${MEILI_PORT}"
    volumes:
      - ./meili_data:/meili_data
      - ./logs/meili:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      MEILI_MASTER_KEY: "${MEILI_KEY}"
    restart: always

  nats:
    image: nats:latest
    # Reducción de la verborragia en la salida.
    command:
      - "-DV=false"
    ports:
      - "4222:4222"
    volumes:
      - ./logs/nats:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  # Servicio de autenticación SuperTokens.
  supertokens:
    image: supertokens/supertokens-core:dev-branch-11.0
    container_name: supertokens
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}"
      # Se reduce la verborragia de la salida, únicamente mostrando warnings.
      SUPERTOKENS_LOG_LEVEL: "warn"
    ports:
      - "${SUPERTOKENS_PORT}:${SUPERTOKENS_PORT}"
    volumes:
      - ./logs/supertokens:/var/log
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  tpe-db-data:
