// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Contenttype struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Review struct {
	ID     int32          `json:"id"`
	UserID sql.NullInt32  `json:"user_id"`
	WorkID sql.NullInt32  `json:"work_id"`
	Score  sql.NullInt32  `json:"score"`
	Review sql.NullString `json:"review"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Work struct {
	ID            int32         `json:"id"`
	Title         string        `json:"title"`
	ContentTypeID int32         `json:"content_type_id"`
	Unit          sql.NullBool  `json:"unit"`
	SagaID        sql.NullInt32 `json:"saga_id"`
}
