// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
/*package views





// ------------------------------------------------------------------------------------------------


templ firstQuery() {


	<div class="inicio">


		<div class="centered-container">


			<div class="inicio-image-container">


				<img src="static/img/logo.png" alt="Logo Scifi" id="logo_scifi"/>


			</div>


			<div class="inicio-query-container">


				<input type="text" id="first-query" placeholder="Search for SCIENCE!!!"/>


			</div>


		</div>


	</div>


	<script>


        const input = document.getElementById("first-query");


        input.addEventListener("keypress", (e) => {


            if (e.key === "Enter") {


                const query = input.value.trim();


                if (!query) return;


                window.location.href = `/search?query=${encodeURIComponent(query)}`;


            }


        });


    </script>


}*/

// ------------------------------------------------------------------------------------------------

package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// ------------------------------------------------------------------------------------------------
func firstQuery() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"[grid-area:inicio] flex justify-center items-center w-full h-full\"><div class=\"h-1/2 w-1/2 grid grid-cols-1 grid-rows-[70%_30%]\"><div class=\"flex justify-center items-center\"><img src=\"static/img/logo.png\" alt=\"Logo Scifi\" id=\"logo_scifi\" class=\"h-full object-contain\"></div><div class=\"flex justify-center items-center\"><input type=\"text\" id=\"first-query\" placeholder=\"Search for SCIENCE!!!\" class=\"\n                        h-[70%] w-[75%] \n                        text-black \n                        rounded-[32px] border-0 \n                        bg-scifi-30 \n                        pl-[40px]\n                        bg-[url('/static/img/icono_busqueda_blanco.svg')] \n                        bg-no-repeat \n                        bg-[10px_10px] \n                        focus:outline-none focus:border-[0.5px] focus:border-black\n                    \"></div></div></div><script>\n        const input = document.getElementById(\"first-query\");\n        input.addEventListener(\"keypress\", (e) => {\n            if (e.key === \"Enter\") {\n                const query = input.value.trim();\n                if (!query) return;\n                window.location.href = `/search?query=${encodeURIComponent(query)}`;\n            }\n        });\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
